"""add_encryption_audit_log_table

Revision ID: 21b2798be632
Revises: 017f33f86833
Create Date: 2025-06-25 19:52:16.571209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21b2798be632'
down_revision: Union[str, Sequence[str], None] = '017f33f86833'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('encryption_audit_log',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('patient_id', sa.String(length=50), nullable=True),
    sa.Column('operation', sa.Enum('encrypt', 'decrypt', name='encryption_operation_enum'), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('key_version', sa.String(length=50), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_encryption_audit_log_id'), 'encryption_audit_log', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_encryption_audit_log_id'), table_name='encryption_audit_log')
    op.drop_table('encryption_audit_log')
    # ### end Alembic commands ###
