"""Add patients and file_uploads tables

Revision ID: a0a80e80bfca
Revises: 1a6a092e6c4f
Create Date: 2025-06-25 00:22:03.269640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0a80e80bfca'
down_revision: Union[str, Sequence[str], None] = '1a6a092e6c4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_uploads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.String(length=255), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('total_records', sa.Integer(), nullable=False),
    sa.Column('successful_records', sa.Integer(), nullable=False),
    sa.Column('failed_records', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('processing', 'completed', 'failed', 'partial', name='upload_status_enum'), nullable=True),
    sa.Column('processing_started_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('processing_completed_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_id')
    )
    op.create_index(op.f('ix_file_uploads_id'), 'file_uploads', ['id'], unique=False)
    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.String(length=50), nullable=False),
    sa.Column('first_name_encrypted', sa.Text(), nullable=False),
    sa.Column('last_name_encrypted', sa.Text(), nullable=False),
    sa.Column('date_of_birth_encrypted', sa.Text(), nullable=False),
    sa.Column('gender_encrypted', sa.Text(), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('encryption_key_version', sa.String(length=50), nullable=False),
    sa.Column('file_upload_batch_id', sa.String(length=255), nullable=True),
    sa.Column('data_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id')
    )
    op.create_index(op.f('ix_patients_id'), 'patients', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patients_id'), table_name='patients')
    op.drop_table('patients')
    op.drop_index(op.f('ix_file_uploads_id'), table_name='file_uploads')
    op.drop_table('file_uploads')
    # ### end Alembic commands ###
