"""Add encryption_keys table

Revision ID: ffa83a545784
Revises: 8e574abf28cb
Create Date: 2025-06-25 01:14:03.464601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffa83a545784'
down_revision: Union[str, Sequence[str], None] = '8e574abf28cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('encryption_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key_version', sa.String(length=50), nullable=False),
    sa.Column('key_hash', sa.String(length=255), nullable=False),
    sa.Column('algorithm', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('rotated_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_version')
    )
    op.create_index(op.f('ix_encryption_keys_id'), 'encryption_keys', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_encryption_keys_id'), table_name='encryption_keys')
    op.drop_table('encryption_keys')
    # ### end Alembic commands ###
